### ISSUE TITLE
Add interactive CRUD calendar 

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#28]
## Calendar 
 - The design should be in line with the minimalist theme the site has so far. 
 - It needs to be able to easily change months and days and be 100% accessible (see: [a11y project](https://a11yproject.com/)) 
 - A side panel with the current day your on and its events is a bonus. 

## CRUD 
- The Netlify Form API may not be enough to handle this eventually and will need another CRM means of handling data from the static site.
- The data will update the calendar at night, once a day... This needs to be communicated to the user.
- Able to add/edit/delete events to the days 
- Need admin approval before being visible to the public ()
- Profanity filtering a bonus 

RFC: Any other suggestions for this feature are welcome.

**Comment by JacobMGEvans** [comment]
@rmcfadzean can you link that gist if you don't mind as well 😁

**Comment by rmcfadzean** [comment]
Here's the message from slack/gist:

-------

I would suggest against having any kind of "CRUD" around the calendar. This is not a wheel worth reinventing, in my opinion.

* Gatsby is extremely adept at parsing source data at build time allowing you to built truly static sites.
* APIs provide needless complexity in this situation
* Gatsby forms have very low limits unless we start paying for the higher tiers

## My suggestions

### Use YAML/JSON/TOML/??

For example

`src/events/2019-10-16.yml`

```yaml
id: october-2019-something-something
date: 2019-10-16
title: October 2019 Meetup
```

`src/talks/building-with-gatsby.yml`

```yaml
title: Building with Gatsby
speaker: rmcfadzean # used as a FK to create relational data
event: october-2019-something-something
description: An introduction to building blazing fast, static/JAMstack websites with Gatsby JS
```

`src/speakers/rmcfadzean.yml`

```yaml
firstName: Rob
lastName: McFadzean
profilePicture: ./assets/images/speakers/rmcfadzean.jpg # Gatsby can turn this into an image sharp node so we can get all the nice transforms and imports on it
social:
  github: rmcfadzean
  website: https://northxsouth.co
company:
  name: North x South
  title: CTO & Developer # eg: For displaying {company.title} @ {company.name}
  website: https://northxsouth.co
```

**Note**: All of these could made relational so that when referencing a speaker from graphql, we could also easily drill down into their talks, events, etc and vice versa.
**Another note**: This is just example schema too. We could add more or less obviously.

#### Wins

* Blazing fast
* Free
* First-class integration with Gatsby
* Easily exportable/moveable later
* Minimal extra setup

#### Drawbacks

* Not friendly to people unfamiliar with Git/Github - *This is only a mild issue as these should only be updated in certain ways, by certain people (in my opinion)*
* (Probably - investigation needed) requires manual syncing to a shareable Google calendar or similar
* Less visiblity than meetup.com (unless crossposted there)


### ~~Meetup.com~~

Removed as a contender.

#### Wins

* Larger visibility
* Full-featured
* Has a [gatsby source](https://github.com/phacks/gatsby-source-meetup) plugin

##### Cons

* Not free - $99/6mo, or $24/mo.
* 3rd party - *Only an issue for if we have to migrate later. see the medium.com / freecodecamp mess for a great example*
  * Turns out they basically did this.


### Google Calendar (or similar)

#### Wins

* Free
* Is a calendar.
* Has a [gatsby source](https://github.com/langovoi/gatsby-source-ical/) plugin

#### Cons

* Less visiblity than meetup.com (unless crossposted there)
